/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewExpenseImport } from './routes/newExpense'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NewExpenseRoute = NewExpenseImport.update({
  id: '/newExpense',
  path: '/newExpense',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/newExpense': {
      id: '/newExpense'
      path: '/newExpense'
      fullPath: '/newExpense'
      preLoaderRoute: typeof NewExpenseImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newExpense': typeof NewExpenseRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/newExpense': typeof NewExpenseRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/newExpense': typeof NewExpenseRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/newExpense'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/newExpense'
  id: '__root__' | '/' | '/newExpense'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewExpenseRoute: typeof NewExpenseRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewExpenseRoute: NewExpenseRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/newExpense"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/newExpense": {
      "filePath": "newExpense.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
